type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
}

type Device @table {
  user: User
  deviceGroup: DeviceGroup
  deviceId: String!
  name: String!
  createdAt: Timestamp!
  lastSeenAt: Timestamp!
  location: String
  description: String
}

type SensorData @table {
  device: Device
  timestamp: Timestamp!
  sensorType: String!
  value: Float!
  unit: String
}

type Command @table {
  device: Device
  user: User
  timestamp: Timestamp!
  commandType: String!
  payload: String!
  status: String
}

type DeviceSetting @table {
  device: Device
  settingName: String!
  value: String!
  updatedAt: Timestamp!
  dataType: String
}

type DeviceGroup @table {
  user: User
  name: String!
  createdAt: Timestamp!
  description: String
}